/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup/route'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as BookSessionRouteImport } from './routes/book-session/route'
import { Route as IndexImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session/$sessionId/route'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/onboarding.lazy').then((d) => d.Route))

const SignupRouteRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRouteRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const BookSessionRouteRoute = BookSessionRouteImport.update({
  id: '/book-session',
  path: '/book-session',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/book-session/route.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SessionSessionIdRouteRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/session/$sessionId/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/book-session': {
      id: '/book-session'
      path: '/book-session'
      fullPath: '/book-session'
      preLoaderRoute: typeof BookSessionRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-session': typeof BookSessionRouteRoute
  '/login': typeof LoginRouteRoute
  '/signup': typeof SignupRouteRoute
  '/onboarding': typeof OnboardingRoute
  '/session/$sessionId': typeof SessionSessionIdRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-session': typeof BookSessionRouteRoute
  '/login': typeof LoginRouteRoute
  '/signup': typeof SignupRouteRoute
  '/onboarding': typeof OnboardingRoute
  '/session/$sessionId': typeof SessionSessionIdRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/book-session': typeof BookSessionRouteRoute
  '/login': typeof LoginRouteRoute
  '/signup': typeof SignupRouteRoute
  '/onboarding': typeof OnboardingRoute
  '/session/$sessionId': typeof SessionSessionIdRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-session'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-session'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/book-session'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookSessionRouteRoute: typeof BookSessionRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  SignupRouteRoute: typeof SignupRouteRoute
  OnboardingRoute: typeof OnboardingRoute
  SessionSessionIdRouteRoute: typeof SessionSessionIdRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookSessionRouteRoute: BookSessionRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  SignupRouteRoute: SignupRouteRoute,
  OnboardingRoute: OnboardingRoute,
  SessionSessionIdRouteRoute: SessionSessionIdRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/book-session",
        "/login",
        "/signup",
        "/onboarding",
        "/session/$sessionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/book-session": {
      "filePath": "book-session/route.tsx"
    },
    "/login": {
      "filePath": "login/route.tsx"
    },
    "/signup": {
      "filePath": "signup/route.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/session/$sessionId": {
      "filePath": "session/$sessionId/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
